version: '2'

services:
  elasticsearch:
    build: ./elasticsearch/
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
      - "./elasticsearch/config:/usr/share/elasticsearch/config"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elk

  logstash:
    build: ./logstash/
    image: logstash:6.6.2
    container_name: logstash
    volumes:
      - "./logstash/config:/usr/share/logstash/config"
      - "./logstash/pipeline:/usr/share/logstash/pipeline"
      - "./logstash/plugin:/usr/share/logstash/plugin"
#      - "./logstash/filebeat-5.6.2:/usr/share/logstash/filebeat"
#      - "/home/docker/Proxy_Nginx/logs:/logs"
#      - "/home/docker/ELK:/temp"
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana/
    image: kibana:6.6.2
    container_name: kibana
    volumes:
      - "./kibana/config:/usr/share/kibana/config"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
#    driver: bridge
