@IP = 127.0.0.1 
@PORT = 5601 

### Create Index Patterns

@ID_1 = My-Patterns-*

POST /api/saved_objects/index-pattern/{{ID_1}} HTTP/1.1
Host: {{IP}}:{{PORT}}
kbn-xsrf: true
Content-Type: application/json

{
  "attributes":
  {
    "title": "{{ID_1}}",
    "timeFieldName" : "@timestamp"
  }
}

### Set Default Index

POST /api/kibana/settings/defaultIndex HTTP/1.1
Host: {{IP}}:{{PORT}}
kbn-xsrf: true
Content-Type: application/json

{
    "value": "{{ID_1}}"
}'

### Delete Index Patterns

@ID_2 = My-Patterns-*

DELETE /api/saved_objects/index-pattern/{{ID_2}} HTTP/1.1
Host: {{IP}}:{{PORT}}
kbn-xsrf: true
