@IP = 10.2.1.103
@PORT = 5601

### Create Index Patterns
@ID_1 = dev-2021.11.*

POST /api/saved_objects/index-pattern/{{ID_1}} HTTP/1.1
Host: {{IP}}:{{PORT}}
kbn-xsrf: true
Content-Type: application/json

{
  "attributes":
  {
    "title": "{{ID_1}}",
    "timeFieldName" : "@timestamp"
  }
}

### Delete Index Patterns
@ID_2 = dev-2021.10.*

DELETE /api/saved_objects/index-pattern/{{ID}} HTTP/1.1
Host: {{IP}}:{{PORT}}
kbn-xsrf: true
