### Create Index Patterns
@ID = dev-2021.10.*
POST /api/saved_objects/index-pattern/{{ID}} HTTP/1.1
Host: 10.2.1.103:5601
kbn-xsrf: true
Content-Type: application/json

{
  "attributes":
  {
    "title": "dev-2021.12.*"
  }
}


### Delete Index Patterns
@ID = dev-2021.10.*
DELETE /api/saved_objects/index-pattern/{{ID}} HTTP/1.1
Host: 10.2.1.103:5601
kbn-xsrf: true